project:
  type: manuscript
  render: 
    - pocp_benchmark_manuscript.qmd

manuscript:
  article: pocp_benchmark_manuscript.qmd

format:
  html: default
  jats: default
  docx: default
  
  # (other formats)
  # pdf: default

execute:
  freeze: false


