project:
  type: manuscript
  render: 
    - pocpbenchmark_manuscript.qmd

manuscript:
  article: pocpbenchmark_manuscript.qmd

format:
  html:
    embed-resources: true
  #jats: default
  docx:
   reference-doc: better-custom-reference-doc.docx
  
  # (other formats)
  # pdf: default

