project:
  type: manuscript
  render: 
    - pocpbenchmark_manuscript.qmd

manuscript:
  article: pocpbenchmark_manuscript.qmd

format:
  html: default
  jats: default
  docx: default
  
  # (other formats)
  # pdf: default

execute:
  freeze: false


